# WordNet, Semantic Relationships and Contextual **Meaning** **bold text**. - ANJALI SINGH - S24CSEU0359

# TASK 1 — WordNet Synsets and **Meanings**

In [ ]:
import nltk
import pandas as pd

# Download required NLTK resources
nltk.download('wordnet')
nltk.download('omw-1.4')

# Import WordNet
from nltk.corpus import wordnet as wn

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

Select at least 10 English **words**

In [ ]:
words = [
    "car",
    "bank",
    "bat",
    "dog",
    "light",
    "plant",
    "book",
    "teacher",
    "student",
    "computer"
]

print("Selected Words:")
print(words)

Selected Words:
['car', 'bank', 'bat', 'dog', 'light', 'plant', 'book', 'teacher', 'student', 'computer']

Display synsets, definitions and **examples**

In [ ]:
q1_results = []

for word in words:

    synsets = wn.synsets(word)

    print("\n" + "=" * 70)
    print("WORD:", word)

    # Display selected synsets
    for synset in synsets[:5]:

        print("\nSynset Name :", synset.name())
        print("Definition  :", synset.definition())

        examples = synset.examples()

        if examples:
            print("Example     :", examples[0])
        else:
            print("Example     : No example available")

        q1_results.append({
            "Word": word,
            "Synset": synset.name(),
            "Definition": synset.definition(),
            "Example": examples[0] if examples else "No example available"
        })

======================================================================
WORD: car

Synset Name : car.n.01
Definition  : a motor vehicle with four wheels; usually propelled by an internal combustion engine
Example     : he needs a car to get to work

Synset Name : car.n.02
Definition  : a wheeled vehicle adapted to the rails of railroad
Example     : three cars had jumped the rails

Synset Name : car.n.03
Definition  : the compartment that is suspended from an airship and that carries personnel and the cargo and the power plant
Example     : No example available

Synset Name : car.n.04
Definition  : where passengers ride up and down
Example     : the car was on the top floor

Synset Name : cable_car.n.01
Definition  : a conveyance for passengers or freight on a cable railway
Example     : they took a cable car to the top of the mountain

======================================================================
WORD: bank

Synset Name : bank.n.01
Definition  : sloping land (especially the slope beside a body of water)
Example     : they pulled the canoe up on the bank

Synset Name : depository_financial_institution.n.01
Definition  : a financial institution that accepts deposits and channels the money into lending activities
Example     : he cashed a check at the bank

Synset Name : bank.n.03
Definition  : a long ridge or pile
Example     : a huge bank of earth

Synset Name : bank.n.04
Definition  : an arrangement of similar objects in a row or in tiers
Example     : he operated a bank of switches

Synset Name : bank.n.05
Definition  : a supply or stock held in reserve for future use (especially in emergencies)
Example     : No example available

======================================================================
WORD: bat

Synset Name : bat.n.01
Definition  : nocturnal mouselike mammal with forelimbs modified to form membranous wings and anatomical adaptations for echolocation by which they navigate
Example     : No example available

Synset Name : bat.n.02
Definition  : (baseball) a turn trying to get a hit
Example     : he was at bat when it happened

Synset Name : squash_racket.n.01
Definition  : a small racket with a long handle used for playing squash
Example     : No example available

Synset Name : cricket_bat.n.01
Definition  : the club used in playing cricket
Example     : a cricket bat has a narrow handle and a broad flat end for hitting

Synset Name : bat.n.05
Definition  : a club used for hitting a ball in various games
Example     : No example available

======================================================================
WORD: dog

Synset Name : dog.n.01
Definition  : a member of the genus Canis (probably descended from the common wolf) that has been domesticated by man since prehistoric times; occurs in many breeds
Example     : the dog barked all night

Synset Name : frump.n.01
Definition  : a dull unattractive unpleasant girl or woman
Example     : she got a reputation as a frump

Synset Name : dog.n.03
Definition  : informal term for a man
Example     : you lucky dog

Synset Name : cad.n.01
Definition  : someone who is morally reprehensible
Example     : you dirty dog

Synset Name : frank.n.02
Definition  : a smooth-textured sausage of minced beef or pork usually smoked; often served on a bread roll
Example     : No example available

======================================================================
WORD: light

Synset Name : light.n.01
Definition  : (physics) electromagnetic radiation that can produce a visual sensation
Example     : the light was filtered through a soft glass window

Synset Name : light.n.02
Definition  : any device serving as a source of illumination
Example     : he stopped the car and turned off the lights

Synset Name : light.n.03
Definition  : a particular perspective or aspect of a situation
Example     : although he saw it in a different light, he still did not understand

Synset Name : luminosity.n.01
Definition  : the quality of being luminous; emitting or reflecting light
Example     : its luminosity is measured relative to that of our sun

Synset Name : light.n.05
Definition  : an illuminated area
Example     : he stepped into the light

======================================================================
WORD: plant

Synset Name : plant.n.01
Definition  : buildings for carrying on industrial labor
Example     : they built a large plant to manufacture automobiles

Synset Name : plant.n.02
Definition  : (botany) a living organism lacking the power of locomotion
Example     : No example available

Synset Name : plant.n.03
Definition  : an actor situated in the audience whose acting is rehearsed but seems spontaneous to the audience
Example     : No example available

Synset Name : plant.n.04
Definition  : something planted secretly for discovery by another
Example     : the police used a plant to trick the thieves

Synset Name : plant.v.01
Definition  : put or set (seeds, seedlings, or plants) into the ground
Example     : Let's plant flowers in the garden

======================================================================
WORD: book

Synset Name : book.n.01
Definition  : a written work or composition that has been published (printed on pages bound together)
Example     : I am reading a good book on economics

Synset Name : book.n.02
Definition  : physical objects consisting of a number of pages bound together
Example     : he used a large book as a doorstop

Synset Name : record.n.05
Definition  : a compilation of the known facts regarding something or someone
Example     : Al Smith used to say, `Let's look at the record'

Synset Name : script.n.01
Definition  : a written version of a play or other dramatic composition; used in preparing for a performance
Example     : No example available

Synset Name : ledger.n.01
Definition  : a record in which commercial accounts are recorded
Example     : they got a subpoena to examine our books

======================================================================
WORD: teacher

Synset Name : teacher.n.01
Definition  : a person whose occupation is teaching
Example     : No example available

Synset Name : teacher.n.02
Definition  : a personified abstraction that teaches
Example     : books were his teachers

======================================================================
WORD: student

Synset Name : student.n.01
Definition  : a learner who is enrolled in an educational institution
Example     : No example available

Synset Name : scholar.n.01
Definition  : a learned person (especially in the humanities); someone who by long study has gained mastery in one or more disciplines
Example     : No example available

======================================================================
WORD: computer

Synset Name : computer.n.01
Definition  : a machine for performing calculations automatically
Example     : No example available

Synset Name : calculator.n.01
Definition  : an expert at calculation (or at operating calculating machines)
Example     : No example available

Create **DataFrame**

In [ ]:
q1_df = pd.DataFrame(q1_results)

print("\nQ1 Synset DataFrame:")
display(q1_df)

Q1 Synset DataFrame:

,Word,Synset,Definition,Example
0,car,car.n.01,a motor vehicle with four wheels; usually prop...,he needs a car to get to work
1,car,car.n.02,a wheeled vehicle adapted to the rails of rail...,three cars had jumped the rails
2,car,car.n.03,the compartment that is suspended from an airs...,No example available
3,car,car.n.04,where passengers ride up and down,the car was on the top floor
4,car,cable_car.n.01,a conveyance for passengers or freight on a ca...,they took a cable car to the top of the mountain
5,bank,bank.n.01,sloping land (especially the slope beside a bo...,they pulled the canoe up on the bank
6,bank,depository_financial_institution.n.01,a financial institution that accepts deposits ...,he cashed a check at the bank
7,bank,bank.n.03,a long ridge or pile,a huge bank of earth
8,bank,bank.n.04,an arrangement of similar objects in a row or ...,he operated a bank of switches
9,bank,bank.n.05,a supply or stock held in reserve for future u...,No example available
10,bat,bat.n.01,nocturnal mouselike mammal with forelimbs modi...,No example available
11,bat,bat.n.02,(baseball) a turn trying to get a hit,he was at bat when it happened
12,bat,squash_racket.n.01,a small racket with a long handle used for pla...,No example available
13,bat,cricket_bat.n.01,the club used in playing cricket,a cricket bat has a narrow handle and a broad ...
14,bat,bat.n.05,a club used for hitting a ball in various games,No example available
15,dog,dog.n.01,a member of the genus Canis (probably descende...,the dog barked all night
16,dog,frump.n.01,a dull unattractive unpleasant girl or woman,she got a reputation as a frump
17,dog,dog.n.03,informal term for a man,you lucky dog
18,dog,cad.n.01,someone who is morally reprehensible,you dirty dog
19,dog,frank.n.02,a smooth-textured sausage of minced beef or po...,No example available
20,light,light.n.01,(physics) electromagnetic radiation that can p...,the light was filtered through a soft glass wi...
21,light,light.n.02,any device serving as a source of illumination,he stopped the car and turned off the lights
22,light,light.n.03,a particular perspective or aspect of a situation,"although he saw it in a different light, he st..."
23,light,luminosity.n.01,the quality of being luminous; emitting or ref...,its luminosity is measured relative to that of...
24,light,light.n.05,an illuminated area,he stepped into the light
25,plant,plant.n.01,buildings for carrying on industrial labor,they built a large plant to manufacture automo...
26,plant,plant.n.02,(botany) a living organism lacking the power o...,No example available
27,plant,plant.n.03,an actor situated in the audience whose acting...,No example available
28,plant,plant.n.04,something planted secretly for discovery by an...,the police used a plant to trick the thieves
29,plant,plant.v.01,"put or set (seeds, seedlings, or plants) into ...",Let's plant flowers in the garden
30,book,book.n.01,a written work or composition that has been pu...,I am reading a good book on economics
31,book,book.n.02,physical objects consisting of a number of pag...,he used a large book as a doorstop
32,book,record.n.05,a compilation of the known facts regarding som...,"Al Smith used to say, `Let's look at the record'"
33,book,script.n.01,a written version of a play or other dramatic ...,No example available
34,book,ledger.n.01,a record in which commercial accounts are reco...,they got a subpoena to examine our books
35,teacher,teacher.n.01,a person whose occupation is teaching,No example available
36,teacher,teacher.n.02,a personified abstraction that teaches,books were his teachers
37,student,student.n.01,a learner who is enrolled in an educational in...,No example available
38,student,scholar.n.01,a learned person (especially in the humanities...,No example available
39,computer,computer.n.01,a machine for performing calculations automati...,No example available
40,computer,calculator.n.01,an expert at calculation (or at operating calc...,No example available

Identify words having multiple **synsets**

In [ ]:
print("\nWords Having Multiple Synsets:\n")

multiple_meaning_words = []

for word in words:

    synsets = wn.synsets(word)

    if len(synsets) > 1:
        multiple_meaning_words.append(word)

        print(word, "->", len(synsets), "synsets")

Words Having Multiple Synsets:

car -> 5 synsets
bank -> 18 synsets
bat -> 10 synsets
dog -> 8 synsets
light -> 47 synsets
plant -> 10 synsets
book -> 15 synsets
teacher -> 2 synsets
student -> 2 synsets
computer -> 2 synsets

Discuss at least 3 multiple-meaning **words**

In [ ]:
print("\n" + "=" * 70)
print("MULTIPLE MEANINGS OF SELECTED WORDS")
print("=" * 70)

selected_multiple_words = ["bank", "bat", "light"]

for word in selected_multiple_words:

    print("\nWord:", word)

    synsets = wn.synsets(word)

    for synset in synsets[:4]:

        print("Synset     :", synset.name())
        print("Definition :", synset.definition())

======================================================================
MULTIPLE MEANINGS OF SELECTED WORDS
======================================================================

Word: bank
Synset     : bank.n.01
Definition : sloping land (especially the slope beside a body of water)
Synset     : depository_financial_institution.n.01
Definition : a financial institution that accepts deposits and channels the money into lending activities
Synset     : bank.n.03
Definition : a long ridge or pile
Synset     : bank.n.04
Definition : an arrangement of similar objects in a row or in tiers

Word: bat
Synset     : bat.n.01
Definition : nocturnal mouselike mammal with forelimbs modified to form membranous wings and anatomical adaptations for echolocation by which they navigate
Synset     : bat.n.02
Definition : (baseball) a turn trying to get a hit
Synset     : squash_racket.n.01
Definition : a small racket with a long handle used for playing squash
Synset     : cricket_bat.n.01
Definition : the club used in playing cricket

Word: light
Synset     : light.n.01
Definition : (physics) electromagnetic radiation that can produce a visual sensation
Synset     : light.n.02
Definition : any device serving as a source of illumination
Synset     : light.n.03
Definition : a particular perspective or aspect of a situation
Synset     : luminosity.n.01
Definition : the quality of being luminous; emitting or reflecting light

# **TASK 2 — Hypernyms and Semantic Hierarchy**

Select at least 10 **nouns**

In [ ]:
noun_words = [
    "car",
    "dog",
    "cat",
    "teacher",
    "student",
    "computer",
    "book",
    "apple",
    "chair",
    "hospital"
]

print("Selected Nouns:")
print(noun_words)

Selected Nouns:
['car', 'dog', 'cat', 'teacher', 'student', 'computer', 'book', 'apple', 'chair', 'hospital']

Select a suitable noun **synset**

In [ ]:
noun_synsets = {}

for word in noun_words:

    synsets = wn.synsets(word, pos=wn.NOUN)

    if synsets:
        noun_synsets[word] = synsets[0]


print("\nSelected Synsets:\n")

for word, synset in noun_synsets.items():
    print(word, "->", synset.name())

Selected Synsets:

car -> car.n.01
dog -> dog.n.01
cat -> cat.n.01
teacher -> teacher.n.01
student -> student.n.01
computer -> computer.n.01
book -> book.n.01
apple -> apple.n.01
chair -> chair.n.01
hospital -> hospital.n.01

Find direct **hypernyms**

In [ ]:
direct_hypernym_results = []

for word, synset in noun_synsets.items():

    hypernyms = synset.hypernyms()

    hypernym_names = [h.name() for h in hypernyms]

    direct_hypernym_results.append({
        "Word": word,
        "Synset": synset.name(),
        "Direct Hypernyms":
            ", ".join(hypernym_names)
            if hypernym_names
            else "None"
    })


direct_hypernym_df = pd.DataFrame(direct_hypernym_results)

print("\nDirect Hypernyms:")
display(direct_hypernym_df)

Direct Hypernyms:

       Word         Synset                   Direct Hypernyms
0       car       car.n.01                 motor_vehicle.n.01
1       dog       dog.n.01  canine.n.02, domestic_animal.n.01
2       cat       cat.n.01                        feline.n.01
3   teacher   teacher.n.01                      educator.n.01
4   student   student.n.01                      enrollee.n.01
5  computer  computer.n.01                       machine.n.01
6      book      book.n.01                   publication.n.01
7     apple     apple.n.01       pome.n.01, edible_fruit.n.01
8     chair     chair.n.01                          seat.n.03
9  hospital  hospital.n.01              medical_building.n.01

Function to trace hypernym **hierarchy**

In [ ]:
def get_hypernym_chain(synset, levels=3):

    chain = []

    current = synset

    for i in range(levels):

        hypernyms = current.hypernyms()

        if not hypernyms:
            break

        current = hypernyms[0]

        chain.append(current.name())

    return chain

Trace hierarchy for all 10 **nouns**

In [ ]:
hierarchy_results = []

for word, synset in noun_synsets.items():

    chain = get_hypernym_chain(
        synset,
        levels=3
    )

    hierarchy_results.append({
        "Word": word,
        "Synset": synset.name(),
        "Hypernym Chain":
            " -> ".join(chain)
            if chain
            else "No hypernym found"
    })

Display final **DataFrame**

In [ ]:
hierarchy_df = pd.DataFrame(hierarchy_results)

print("\nHypernym Hierarchy:")
display(hierarchy_df)

Hypernym Hierarchy:

       Word         Synset                                     Hypernym Chain
0       car       car.n.01  motor_vehicle.n.01 -> self-propelled_vehicle.n...
1       dog       dog.n.01    canine.n.02 -> carnivore.n.01 -> placental.n.01
2       cat       cat.n.01    feline.n.01 -> carnivore.n.01 -> placental.n.01
3   teacher   teacher.n.01   educator.n.01 -> professional.n.01 -> adult.n.01
4   student   student.n.01      enrollee.n.01 -> person.n.01 -> organism.n.01
5  computer  computer.n.01  machine.n.01 -> device.n.01 -> instrumentality...
6      book      book.n.01      publication.n.01 -> work.n.02 -> product.n.02
7     apple     apple.n.01  pome.n.01 -> fruit.n.01 -> reproductive_struct...
8     chair     chair.n.01     seat.n.03 -> furniture.n.01 -> furnishing.n.02
9  hospital  hospital.n.01  medical_building.n.01 -> building.n.01 -> stru...

# **TASK 3 — WordNet Semantic Similarity**

Select at least 8 word **pairs**

In [ ]:
word_pairs = [
    ("car", "automobile"),
    ("dog", "cat"),
    ("dog", "animal"),
    ("dog", "computer"),
    ("car", "vehicle"),
    ("apple", "banana"),
    ("teacher", "student"),
    ("computer", "book")
]

print("Selected Word Pairs:\n")

for pair in word_pairs:
    print(pair)

Selected Word Pairs:

('car', 'automobile')
('dog', 'cat')
('dog', 'animal')
('dog', 'computer')
('car', 'vehicle')
('apple', 'banana')
('teacher', 'student')
('computer', 'book')

Calculate WordNet path **similarity**

In [ ]:
similarity_results = []

for word1, word2 in word_pairs:

    synsets1 = wn.synsets(word1, pos=wn.NOUN)
    synsets2 = wn.synsets(word2, pos=wn.NOUN)

    if synsets1 and synsets2:

        synset1 = synsets1[0]
        synset2 = synsets2[0]

        similarity = synset1.path_similarity(synset2)

        similarity_results.append({
            "Word 1": word1,
            "Word 2": word2,
            "Synset 1": synset1.name(),
            "Synset 2": synset2.name(),
            "Path Similarity": similarity
        })

**store** results in DataFrame

In [ ]:
similarity_df = pd.DataFrame(similarity_results)

print("\nSemantic Similarity Results:")
display(similarity_df)

Semantic Similarity Results:

     Word 1      Word 2       Synset 1       Synset 2  Path Similarity
0       car  automobile       car.n.01       car.n.01         1.000000
1       dog         cat       dog.n.01       cat.n.01         0.200000
2       dog      animal       dog.n.01    animal.n.01         0.333333
3       dog    computer       dog.n.01  computer.n.01         0.090909
4       car     vehicle       car.n.01   vehicle.n.01         0.200000
5     apple      banana     apple.n.01    banana.n.01         0.071429
6   teacher     student   teacher.n.01   student.n.01         0.142857
7  computer        book  computer.n.01      book.n.01         0.100000

Rank pairs by similarity **score**

In [ ]:
ranked_similarity_df = similarity_df.sort_values(
    by="Path Similarity",
    ascending=False
).reset_index(drop=True)

print("\nRanked Similarity Results:")
display(ranked_similarity_df)

Ranked Similarity Results:

     Word 1      Word 2       Synset 1       Synset 2  Path Similarity
0       car  automobile       car.n.01       car.n.01         1.000000
1       dog      animal       dog.n.01    animal.n.01         0.333333
2       dog         cat       dog.n.01       cat.n.01         0.200000
3       car     vehicle       car.n.01   vehicle.n.01         0.200000
4   teacher     student   teacher.n.01   student.n.01         0.142857
5  computer        book  computer.n.01      book.n.01         0.100000
6       dog    computer       dog.n.01  computer.n.01         0.090909
7     apple      banana     apple.n.01    banana.n.01         0.071429

Explain the **results**

In [ ]:
print("\nObservations:")
print()

print("1. car and automobile are highly similar because")
print("   they represent nearly the same concept.")

print()

print("2. dog and cat are similar because both are animals")
print("   and belong to related semantic categories.")

print()

print("3. dog and animal are related because a dog is")
print("   a type of animal.")

print()

print("4. dog and computer are dissimilar because they")
print("   belong to very different semantic categories.")

print()

print("5. Higher path similarity means the two synsets")
print("   are closer in the WordNet semantic hierarchy.")

Observations:

1. car and automobile are highly similar because
   they represent nearly the same concept.

2. dog and cat are similar because both are animals
   and belong to related semantic categories.

3. dog and animal are related because a dog is
   a type of animal.

4. dog and computer are dissimilar because they
   belong to very different semantic categories.

5. Higher path similarity means the two synsets
   are closer in the WordNet semantic hierarchy.

# **TASK 4 — Homonyms and Contextual Meaning**

Create two sentences for each **homonym**

In [ ]:
contextual_data = [

    # BANK
    {
        "Word": "bank",
        "Sentence": "I deposited money in the bank.",
        "Intended Meaning": "Financial institution",
        "Contextual Clue": "deposited money"
    },

    {
        "Word": "bank",
        "Sentence": "We sat on the bank of the river.",
        "Intended Meaning": "Side of a river",
        "Contextual Clue": "river"
    },


    # BAT
    {
        "Word": "bat",
        "Sentence": "The bat flew out of the cave.",
        "Intended Meaning": "Flying mammal",
        "Contextual Clue": "flew, cave"
    },

    {
        "Word": "bat",
        "Sentence": "He hit the ball with a bat.",
        "Intended Meaning": "Sports equipment",
        "Contextual Clue": "hit the ball"
    },


    # BARK
    {
        "Word": "bark",
        "Sentence": "The dog's bark was very loud.",
        "Intended Meaning": "Sound made by a dog",
        "Contextual Clue": "dog, loud"
    },

    {
        "Word": "bark",
        "Sentence": "The bark of the tree was rough.",
        "Intended Meaning": "Outer covering of a tree",
        "Contextual Clue": "tree, rough"
    },


    # LIGHT
    {
        "Word": "light",
        "Sentence": "The room needs more light.",
        "Intended Meaning": "Illumination",
        "Contextual Clue": "room"
    },

    {
        "Word": "light",
        "Sentence": "This bag is very light.",
        "Intended Meaning": "Not heavy",
        "Contextual Clue": "bag, weight"
    },


    # MATCH
    {
        "Word": "match",
        "Sentence": "He lit the candle with a match.",
        "Intended Meaning": "Small stick used to make fire",
        "Contextual Clue": "lit the candle"
    },

    {
        "Word": "match",
        "Sentence": "Our team won the football match.",
        "Intended Meaning": "Sports game or contest",
        "Contextual Clue": "football, team"
    }
]


context_df = pd.DataFrame(contextual_data)

print("Contextual Sentences:")
display(context_df)

Contextual Sentences:

,Word,Sentence,Intended Meaning,Contextual Clue
0,bank,I deposited money in the bank.,Financial institution,deposited money
1,bank,We sat on the bank of the river.,Side of a river,river
2,bat,The bat flew out of the cave.,Flying mammal,"flew, cave"
3,bat,He hit the ball with a bat.,Sports equipment,hit the ball
4,bark,The dog's bark was very loud.,Sound made by a dog,"dog, loud"
5,bark,The bark of the tree was rough.,Outer covering of a tree,"tree, rough"
6,light,The room needs more light.,Illumination,room
7,light,This bag is very light.,Not heavy,"bag, weight"
8,match,He lit the candle with a match.,Small stick used to make fire,lit the candle
9,match,Our team won the football match.,Sports game or contest,"football, team"

Display WordNet **synsets**

In [ ]:
homonyms = [
    "bank",
    "bat",
    "bark",
    "light",
    "match"
]

print("\n" + "=" * 70)
print("WORDNET SYNSETS OF HOMONYMS")
print("=" * 70)


for word in homonyms:

    print("\nWORD:", word)

    synsets = wn.synsets(word)

    for synset in synsets[:5]:

        print("\nSynset     :", synset.name())
        print("Definition :", synset.definition())

        examples = synset.examples()

        if examples:
            print("Example    :", examples[0])

======================================================================
WORDNET SYNSETS OF HOMONYMS
======================================================================

WORD: bank

Synset     : bank.n.01
Definition : sloping land (especially the slope beside a body of water)
Example    : they pulled the canoe up on the bank

Synset     : depository_financial_institution.n.01
Definition : a financial institution that accepts deposits and channels the money into lending activities
Example    : he cashed a check at the bank

Synset     : bank.n.03
Definition : a long ridge or pile
Example    : a huge bank of earth

Synset     : bank.n.04
Definition : an arrangement of similar objects in a row or in tiers
Example    : he operated a bank of switches

Synset     : bank.n.05
Definition : a supply or stock held in reserve for future use (especially in emergencies)

WORD: bat

Synset     : bat.n.01
Definition : nocturnal mouselike mammal with forelimbs modified to form membranous wings and anatomical adaptations for echolocation by which they navigate

Synset     : bat.n.02
Definition : (baseball) a turn trying to get a hit
Example    : he was at bat when it happened

Synset     : squash_racket.n.01
Definition : a small racket with a long handle used for playing squash

Synset     : cricket_bat.n.01
Definition : the club used in playing cricket
Example    : a cricket bat has a narrow handle and a broad flat end for hitting

Synset     : bat.n.05
Definition : a club used for hitting a ball in various games

WORD: bark

Synset     : bark.n.01
Definition : tough protective covering of the woody stems and roots of trees and other woody plants

Synset     : bark.n.02
Definition : a noise resembling the bark of a dog

Synset     : bark.n.03
Definition : a sailing ship with 3 (or more) masts

Synset     : bark.n.04
Definition : the sound made by a dog

Synset     : bark.v.01
Definition : speak in an unfriendly tone
Example    : She barked into the dictaphone

WORD: light

Synset     : light.n.01
Definition : (physics) electromagnetic radiation that can produce a visual sensation
Example    : the light was filtered through a soft glass window

Synset     : light.n.02
Definition : any device serving as a source of illumination
Example    : he stopped the car and turned off the lights

Synset     : light.n.03
Definition : a particular perspective or aspect of a situation
Example    : although he saw it in a different light, he still did not understand

Synset     : luminosity.n.01
Definition : the quality of being luminous; emitting or reflecting light
Example    : its luminosity is measured relative to that of our sun

Synset     : light.n.05
Definition : an illuminated area
Example    : he stepped into the light

WORD: match

Synset     : match.n.01
Definition : lighter consisting of a thin piece of wood or cardboard tipped with combustible chemical; ignites with friction
Example    : he always carries matches to light his pipe

Synset     : match.n.02
Definition : a formal contest in which two or more persons or teams compete

Synset     : match.n.03
Definition : a burning piece of wood or cardboard
Example    : if you drop a match in there the whole place will explode

Synset     : match.n.04
Definition : an exact duplicate
Example    : when a match is found an entry is made in the notebook

Synset     : match.n.05
Definition : the score needed to win a match

 Compare contextual **sentences**

In [ ]:
print("\n" + "=" * 70)
print("CONTEXTUAL MEANING ANALYSIS")
print("=" * 70)


for index, row in context_df.iterrows():

    print("\nWord:", row["Word"])
    print("Sentence:", row["Sentence"])
    print("Intended Meaning:", row["Intended Meaning"])
    print("Contextual Clue:", row["Contextual Clue"])

======================================================================
CONTEXTUAL MEANING ANALYSIS
======================================================================

Word: bank
Sentence: I deposited money in the bank.
Intended Meaning: Financial institution
Contextual Clue: deposited money

Word: bank
Sentence: We sat on the bank of the river.
Intended Meaning: Side of a river
Contextual Clue: river

Word: bat
Sentence: The bat flew out of the cave.
Intended Meaning: Flying mammal
Contextual Clue: flew, cave

Word: bat
Sentence: He hit the ball with a bat.
Intended Meaning: Sports equipment
Contextual Clue: hit the ball

Word: bark
Sentence: The dog's bark was very loud.
Intended Meaning: Sound made by a dog
Contextual Clue: dog, loud

Word: bark
Sentence: The bark of the tree was rough.
Intended Meaning: Outer covering of a tree
Contextual Clue: tree, rough

Word: light
Sentence: The room needs more light.
Intended Meaning: Illumination
Contextual Clue: room

Word: light
Sentence: This bag is very light.
Intended Meaning: Not heavy
Contextual Clue: bag, weight

Word: match
Sentence: He lit the candle with a match.
Intended Meaning: Small stick used to make fire
Contextual Clue: lit the candle

Word: match
Sentence: Our team won the football match.
Intended Meaning: Sports game or contest
Contextual Clue: football, team

Explain how context determines **meaning**

In [ ]:
print("\n" + "=" * 70)
print("CONTEXTUAL OBSERVATIONS")
print("=" * 70)

print("""
1. In "deposited money in the bank", the words
   "deposited money" indicate a financial institution.

2. In "bank of the river", the word "river" indicates
   that bank means the side of a river.

3. In "bat flew out of the cave", the words
   "flew" and "cave" indicate the animal.

4. In "hit the ball with a bat", the words
   "hit the ball" indicate sports equipment.

5. In "tree bark", the word "tree" indicates the
   outer covering of a tree.

Therefore, surrounding words provide context and help
determine the intended meaning of a word.
""")

======================================================================
CONTEXTUAL OBSERVATIONS
======================================================================

1. In "deposited money in the bank", the words
   "deposited money" indicate a financial institution.

2. In "bank of the river", the word "river" indicates
   that bank means the side of a river.

3. In "bat flew out of the cave", the words
   "flew" and "cave" indicate the animal.

4. In "hit the ball with a bat", the words
   "hit the ball" indicate sports equipment.

5. In "tree bark", the word "tree" indicates the
   outer covering of a tree.

Therefore, surrounding words provide context and help
determine the intended meaning of a word.

 Final comparison table

In [ ]:
final_context_df = context_df[
    [
        "Word",
        "Sentence",
        "Intended Meaning",
        "Contextual Clue"
    ]
]

print("\nFinal Contextual Meaning Table:")
display(final_context_df)

Final Contextual Meaning Table:

,Word,Sentence,Intended Meaning,Contextual Clue
0,bank,I deposited money in the bank.,Financial institution,deposited money
1,bank,We sat on the bank of the river.,Side of a river,river
2,bat,The bat flew out of the cave.,Flying mammal,"flew, cave"
3,bat,He hit the ball with a bat.,Sports equipment,hit the ball
4,bark,The dog's bark was very loud.,Sound made by a dog,"dog, loud"
5,bark,The bark of the tree was rough.,Outer covering of a tree,"tree, rough"
6,light,The room needs more light.,Illumination,room
7,light,This bag is very light.,Not heavy,"bag, weight"
8,match,He lit the candle with a match.,Small stick used to make fire,lit the candle
9,match,Our team won the football match.,Sports game or contest,"football, team"

# **conclusion**

In this lab, we explored WordNet and lexical semantics by studying synsets, word meanings, hypernyms, and semantic similarity. We also analyzed homonyms and learned how the context of a sentence helps determine the correct meaning of a word. Overall, the lab showed how semantic relationships and context are important for understanding natural language.