# NLP Lab 1 – Text Preprocessing and N-gram Analysis

**Name:** Satyam Kumar  
**Enrollment No.:** S24CSEU0480  
**Course:** Natural Language Processing  
**Course Code:** CSET346  
**Batch:** 2026-27

In [ ]:
# Install required libraries
!pip install nltk pandas

Requirement already satisfied: nltk in /usr/local/lib/python3.13/dist-packages (3.9.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: click in /usr/local/lib/python3.13/dist-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.13/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# Import NLTK
import nltk

# Download required NLTK datasets
nltk.download('brown')
nltk.download('gutenberg')
nltk.download('words')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt')
nltk.download('punkt_tab')

print("All NLTK resources downloaded successfully!")

[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Unzipping corpora/brown.zip.
[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Unzipping corpora/gutenberg.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

All NLTK resources downloaded successfully!

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [ ]:
from nltk.corpus import brown

# Load Brown Corpus
sentences = brown.sents()[:20]

print("Number of selected sentences:", len(sentences))

Number of selected sentences: 20

In [ ]:
print("First 20 sentences from Brown Corpus:\n")

for i, sentence in enumerate(sentences, start=1):
    print(i, ".", " ".join(sentence))

First 20 sentences from Brown Corpus:

1 . The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced `` no evidence '' that any irregularities took place .
2 . The jury further said in term-end presentments that the City Executive Committee , which had over-all charge of the election , `` deserves the praise and thanks of the City of Atlanta '' for the manner in which the election was conducted .
3 . The September-October term jury had been charged by Fulton Superior Court Judge Durwood Pye to investigate reports of possible `` irregularities '' in the hard-fought primary which was won by Mayor-nominate Ivan Allen Jr. .
4 . `` Only a relative handful of such reports was received '' , the jury said , `` considering the widespread interest in the election , the number of voters and the size of this city '' .
5 . The jury said it did find that many of Georgia's registration and election laws `` are outmoded or inadequate and often ambiguous '' .
6 . It recommended that Fulton legislators act `` to have these laws studied and revised to the end of modernizing and improving them '' .
7 . The grand jury commented on a number of other topics , among them the Atlanta and Fulton County purchasing departments which it said `` are well operated and follow generally accepted practices which inure to the best interest of both governments '' .
8 . Merger proposed
9 . However , the jury said it believes `` these two offices should be combined to achieve greater efficiency and reduce the cost of administration '' .
10 . The City Purchasing Department , the jury said , `` is lacking in experienced clerical personnel as a result of city personnel policies '' .
11 . It urged that the city `` take steps to remedy '' this problem .
12 . Implementation of Georgia's automobile title law was also recommended by the outgoing jury .
13 . It urged that the next Legislature `` provide enabling funds and re-set the effective date so that an orderly implementation of the law may be effected '' .
14 . The grand jury took a swipe at the State Welfare Department's handling of federal funds granted for child welfare services in foster homes .
15 . `` This is one of the major items in the Fulton County general assistance program '' , the jury said , but the State Welfare Department `` has seen fit to distribute these funds through the welfare departments of all the counties in the state with the exception of Fulton County , which receives none of this money .
16 . The jurors said they realize `` a proportionate distribution of these funds might disable this program in our less populous counties '' .
17 . Nevertheless , `` we feel that in the future Fulton County should receive some portion of these available funds '' , the jurors said .
18 . `` Failure to do this will continue to place a disproportionate burden '' on Fulton taxpayers .
19 . The jury also commented on the Fulton ordinary's court which has been under fire for its practices in the appointment of appraisers , guardians and administrators and the awarding of fees and compensation .
20 . Wards protected

In [ ]:
from nltk.tokenize import sent_tokenize

# Join the Brown Corpus sentences into one text
text = " ".join(" ".join(sentence) for sentence in sentences)

# Sentence tokenization
sentence_tokens = sent_tokenize(text)

print("Number of sentence tokens:", len(sentence_tokens))

print("\nFirst 5 sentence tokens:")
for i, sentence in enumerate(sentence_tokens[:5], start=1):
    print(i, ".", sentence)

Number of sentence tokens: 19

First 5 sentence tokens:
1 . The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced `` no evidence '' that any irregularities took place .
2 . The jury further said in term-end presentments that the City Executive Committee , which had over-all charge of the election , `` deserves the praise and thanks of the City of Atlanta '' for the manner in which the election was conducted .
3 . The September-October term jury had been charged by Fulton Superior Court Judge Durwood Pye to investigate reports of possible `` irregularities '' in the hard-fought primary which was won by Mayor-nominate Ivan Allen Jr. .
4 . `` Only a relative handful of such reports was received '' , the jury said , `` considering the widespread interest in the election , the number of voters and the size of this city '' .
5 . The jury said it did find that many of Georgia's registration and election laws `` are outmoded or inadequate and often ambiguous '' .

In [ ]:
from nltk.tokenize import word_tokenize

# Word tokenization of the first sentence
words = word_tokenize(sentence_tokens[0])

print("Original sentence:")
print(sentence_tokens[0])

print("\nWord tokens:")
print(words)

Original sentence:
The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced `` no evidence '' that any irregularities took place .

Word tokens:
['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', 'Friday', 'an', 'investigation', 'of', 'Atlanta', "'s", 'recent', 'primary', 'election', 'produced', '``', 'no', 'evidence', '``', 'that', 'any', 'irregularities', 'took', 'place', '.']

In [ ]:
from nltk.corpus import stopwords
import string

# Load English stopwords
stop_words = set(stopwords.words('english'))

cleaned_sentences = []

for sentence in sentence_tokens:

    # Word tokenization
    words = word_tokenize(sentence)

    # Convert to lowercase
    # Keep only alphabetic words
    # Remove stopwords
    cleaned_words = [
        word.lower()
        for word in words
        if word.isalpha() and word.lower() not in stop_words
    ]

    cleaned_sentences.append(cleaned_words)

print("Cleaning completed successfully!")

Cleaning completed successfully!

In [ ]:
for i in range(5):

    print("=" * 60)
    print("SENTENCE", i + 1)

    print("\nOriginal Sentence:")
    print(sentence_tokens[i])

    print("\nOriginal Word Tokens:")
    print(word_tokenize(sentence_tokens[i]))

    print("\nCleaned Tokens:")
    print(cleaned_sentences[i])

============================================================
SENTENCE 1

Original Sentence:
The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced `` no evidence '' that any irregularities took place .

Original Word Tokens:
['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', 'Friday', 'an', 'investigation', 'of', 'Atlanta', "'s", 'recent', 'primary', 'election', 'produced', '``', 'no', 'evidence', '``', 'that', 'any', 'irregularities', 'took', 'place', '.']

Cleaned Tokens:
['fulton', 'county', 'grand', 'jury', 'said', 'friday', 'investigation', 'atlanta', 'recent', 'primary', 'election', 'produced', 'evidence', 'irregularities', 'took', 'place']
============================================================
SENTENCE 2

Original Sentence:
The jury further said in term-end presentments that the City Executive Committee , which had over-all charge of the election , `` deserves the praise and thanks of the City of Atlanta '' for the manner in which the election was conducted .

Original Word Tokens:
['The', 'jury', 'further', 'said', 'in', 'term-end', 'presentments', 'that', 'the', 'City', 'Executive', 'Committee', ',', 'which', 'had', 'over-all', 'charge', 'of', 'the', 'election', ',', '``', 'deserves', 'the', 'praise', 'and', 'thanks', 'of', 'the', 'City', 'of', 'Atlanta', '``', 'for', 'the', 'manner', 'in', 'which', 'the', 'election', 'was', 'conducted', '.']

Cleaned Tokens:
['jury', 'said', 'presentments', 'city', 'executive', 'committee', 'charge', 'election', 'deserves', 'praise', 'thanks', 'city', 'atlanta', 'manner', 'election', 'conducted']
============================================================
SENTENCE 3

Original Sentence:
The September-October term jury had been charged by Fulton Superior Court Judge Durwood Pye to investigate reports of possible `` irregularities '' in the hard-fought primary which was won by Mayor-nominate Ivan Allen Jr. .

Original Word Tokens:
['The', 'September-October', 'term', 'jury', 'had', 'been', 'charged', 'by', 'Fulton', 'Superior', 'Court', 'Judge', 'Durwood', 'Pye', 'to', 'investigate', 'reports', 'of', 'possible', '``', 'irregularities', '``', 'in', 'the', 'hard-fought', 'primary', 'which', 'was', 'won', 'by', 'Mayor-nominate', 'Ivan', 'Allen', 'Jr.', '.']

Cleaned Tokens:
['term', 'jury', 'charged', 'fulton', 'superior', 'court', 'judge', 'durwood', 'pye', 'investigate', 'reports', 'possible', 'irregularities', 'primary', 'ivan', 'allen']
============================================================
SENTENCE 4

Original Sentence:
`` Only a relative handful of such reports was received '' , the jury said , `` considering the widespread interest in the election , the number of voters and the size of this city '' .

Original Word Tokens:
['``', 'Only', 'a', 'relative', 'handful', 'of', 'such', 'reports', 'was', 'received', '``', ',', 'the', 'jury', 'said', ',', '``', 'considering', 'the', 'widespread', 'interest', 'in', 'the', 'election', ',', 'the', 'number', 'of', 'voters', 'and', 'the', 'size', 'of', 'this', 'city', '``', '.']

Cleaned Tokens:
['relative', 'handful', 'reports', 'received', 'jury', 'said', 'considering', 'widespread', 'interest', 'election', 'number', 'voters', 'size', 'city']
============================================================
SENTENCE 5

Original Sentence:
The jury said it did find that many of Georgia's registration and election laws `` are outmoded or inadequate and often ambiguous '' .

Original Word Tokens:
['The', 'jury', 'said', 'it', 'did', 'find', 'that', 'many', 'of', 'Georgia', "'s", 'registration', 'and', 'election', 'laws', '``', 'are', 'outmoded', 'or', 'inadequate', 'and', 'often', 'ambiguous', '``', '.']

Cleaned Tokens:
['jury', 'said', 'find', 'many', 'georgia', 'registration', 'election', 'laws', 'outmoded', 'inadequate', 'often', 'ambiguous']

In [ ]:
from nltk.corpus import brown

# Get alphabetic words from Brown Corpus
brown_words = [
    word.lower()
    for word in brown.words()
    if word.isalpha()
]

# Required words from the question
required_words = [
    "playing",
    "studies",
    "running",
    "better",
    "cars"
]

# Select 30 Brown Corpus words
selected_words = brown_words[:30]

# Add required words
selected_words.extend(required_words)

# Remove duplicates
selected_words = list(dict.fromkeys(selected_words))

print("Total words:", len(selected_words))
print(selected_words)

Total words: 30
['the', 'fulton', 'county', 'grand', 'jury', 'said', 'friday', 'an', 'investigation', 'of', 'recent', 'primary', 'election', 'produced', 'no', 'evidence', 'that', 'any', 'irregularities', 'took', 'place', 'further', 'in', 'presentments', 'city', 'playing', 'studies', 'running', 'better', 'cars']

In [ ]:
from nltk.stem import PorterStemmer

# Create Porter Stemmer
stemmer = PorterStemmer()

# Test some words
test_words = [
    "playing",
    "studies",
    "running",
    "better",
    "cars"
]

print("Original -> Stemmed")

for word in test_words:
    print(word, "->", stemmer.stem(word))

Original -> Stemmed
playing -> play
studies -> studi
running -> run
better -> better
cars -> car

In [ ]:
from nltk.stem import WordNetLemmatizer

# Create lemmatizer
lemmatizer = WordNetLemmatizer()

print("Original -> Lemmatized")

for word in test_words:
    print(word, "->", lemmatizer.lemmatize(word))

Original -> Lemmatized
playing -> playing
studies -> study
running -> running
better -> better
cars -> car

In [ ]:
import pandas as pd

comparison = []

for word in selected_words:

    stemmed = stemmer.stem(word)
    lemmatized = lemmatizer.lemmatize(word)

    comparison.append([
        word,
        stemmed,
        lemmatized
    ])

# Create DataFrame
df = pd.DataFrame(
    comparison,
    columns=[
        "Original Word",
        "Stemmed Word",
        "Lemmatized Word"
    ]
)

display(df)

     Original Word Stemmed Word Lemmatized Word
0              the          the             the
1           fulton       fulton          fulton
2           county       counti          county
3            grand        grand           grand
4             jury         juri            jury
5             said         said            said
6           friday       friday          friday
7               an           an              an
8    investigation     investig   investigation
9               of           of              of
10          recent       recent          recent
11         primary      primari         primary
12        election        elect        election
13        produced       produc        produced
14              no           no              no
15        evidence         evid        evidence
16            that         that            that
17             any          ani             any
18  irregularities    irregular    irregularity
19            took         took            took
20           place        place           place
21         further      further         further
22              in           in              in
23    presentments      present     presentment
24            city         citi            city
25         playing         play         playing
26         studies        studi           study
27         running          run         running
28          better       better          better
29            cars          car             car

In [ ]:
from nltk.corpus import words

# Load English vocabulary
word_list = set(
    word.lower()
    for word in words.words()
    if word.isalpha()
)

print("Number of vocabulary words:", len(word_list))

Number of vocabulary words: 234375

In [ ]:
misspelled_words = [
    "recieve",
    "becuase",
    "enviroment",
    "seperate",
    "definately",
    "occured",
    "langauge",
    "programing",
    "studing",
    "teh"
]

print("Misspelled words:")
for word in misspelled_words:
    print(word)

Misspelled words:
recieve
becuase
enviroment
seperate
definately
occured
langauge
programing
studing
teh

In [ ]:
from difflib import get_close_matches

def correct_word(word):

    suggestions = get_close_matches(
        word.lower(),
        word_list,
        n=1,
        cutoff=0.6
    )

    if suggestions:
        return suggestions[0]

    return "No suggestion"

In [ ]:
results = []

for word in misspelled_words:

    suggestion = correct_word(word)

    results.append([
        word,
        suggestion
    ])

spelling_df = pd.DataFrame(
    results,
    columns=[
        "Misspelled Word",
        "Suggested Correction"
    ]
)

display(spelling_df)

  Misspelled Word Suggested Correction
0         recieve            reachieve
1         becuase              bedcase
2      enviroment          environment
3        seperate              sperate
4      definately           definitely
5         occured                occur
6        langauge             language
7      programing          progambling
8         studing             studding
9             teh                 teth

In [ ]:
example_sentences = [
    "I recieve many messages every day.",
    "Python is a powerfull programing langauge.",
    "We should protect the enviroment.",
    "She is definately studing NLP.",
    "The error occured becuase of a seperate problem."
]

for sentence in example_sentences:

    print("\nOriginal:")
    print(sentence)

    words_in_sentence = word_tokenize(sentence)

    corrected_words = []

    for word in words_in_sentence:

        if word.isalpha():
            corrected_words.append(correct_word(word))
        else:
            corrected_words.append(word)

    corrected_sentence = " ".join(corrected_words)

    # Fix spaces before punctuation
    corrected_sentence = corrected_sentence.replace(" ,", ",")
    corrected_sentence = corrected_sentence.replace(" .", ".")
    corrected_sentence = corrected_sentence.replace(" !", "!")
    corrected_sentence = corrected_sentence.replace(" ?", "?")

    print("Corrected:")
    print(corrected_sentence)

Original:
I recieve many messages every day.
Corrected:
i reachieve many message every day.

Original:
Python is a powerfull programing langauge.
Corrected:
python is a powerfully progambling language.

Original:
We should protect the enviroment.
Corrected:
we should protect the environment.

Original:
She is definately studing NLP.
Corrected:
she is definitely studding unlap.

Original:
The error occured becuase of a seperate problem.
Corrected:
the error occur bedcase of a sperate problem.

# Q4 – Unigram, Bigram and Trigram Analysis

In [ ]:
from nltk.corpus import brown

# Select first 10,000 words from Brown Corpus
subset_words = brown.words()[:10000]

# Keep only alphabetic words and convert to lowercase
clean_words = [
    word.lower()
    for word in subset_words
    if word.isalpha()
]

print("Number of cleaned words:", len(clean_words))

print("\nFirst 50 words:")
print(clean_words[:50])

Number of cleaned words: 8555

First 50 words:
['the', 'fulton', 'county', 'grand', 'jury', 'said', 'friday', 'an', 'investigation', 'of', 'recent', 'primary', 'election', 'produced', 'no', 'evidence', 'that', 'any', 'irregularities', 'took', 'place', 'the', 'jury', 'further', 'said', 'in', 'presentments', 'that', 'the', 'city', 'executive', 'committee', 'which', 'had', 'charge', 'of', 'the', 'election', 'deserves', 'the', 'praise', 'and', 'thanks', 'of', 'the', 'city', 'of', 'atlanta', 'for', 'the']

In [ ]:
from nltk.util import ngrams

# Generate unigrams
unigrams = list(ngrams(clean_words, 1))

# Generate bigrams
bigrams = list(ngrams(clean_words, 2))

# Generate trigrams
trigrams = list(ngrams(clean_words, 3))

print("First 10 Unigrams:")
print(unigrams[:10])

print("\nFirst 10 Bigrams:")
print(bigrams[:10])

print("\nFirst 10 Trigrams:")
print(trigrams[:10])

First 10 Unigrams:
[('the',), ('fulton',), ('county',), ('grand',), ('jury',), ('said',), ('friday',), ('an',), ('investigation',), ('of',)]

First 10 Bigrams:
[('the', 'fulton'), ('fulton', 'county'), ('county', 'grand'), ('grand', 'jury'), ('jury', 'said'), ('said', 'friday'), ('friday', 'an'), ('an', 'investigation'), ('investigation', 'of'), ('of', 'recent')]

First 10 Trigrams:
[('the', 'fulton', 'county'), ('fulton', 'county', 'grand'), ('county', 'grand', 'jury'), ('grand', 'jury', 'said'), ('jury', 'said', 'friday'), ('said', 'friday', 'an'), ('friday', 'an', 'investigation'), ('an', 'investigation', 'of'), ('investigation', 'of', 'recent'), ('of', 'recent', 'primary')]

In [ ]:
from collections import Counter

# Calculate frequencies
unigram_freq = Counter(unigrams)
bigram_freq = Counter(bigrams)
trigram_freq = Counter(trigrams)

print("N-gram frequencies calculated successfully!")

N-gram frequencies calculated successfully!

In [ ]:
print("TOP 10 UNIGRAMS")
print("=" * 40)

for gram, frequency in unigram_freq.most_common(10):

    print(gram, ":", frequency)

TOP 10 UNIGRAMS
========================================
('the',) : 675
('of',) : 315
('to',) : 265
('a',) : 207
('in',) : 195
('and',) : 174
('for',) : 110
('that',) : 99
('would',) : 80
('said',) : 76

In [ ]:
print("TOP 10 BIGRAMS")
print("=" * 40)

for gram, frequency in bigram_freq.most_common(10):

    print(gram, ":", frequency)

TOP 10 BIGRAMS
========================================
('of', 'the') : 95
('in', 'the') : 66
('to', 'the') : 34
('that', 'the') : 23
('on', 'the') : 23
('for', 'the') : 22
('would', 'be') : 22
('the', 'state') : 18
('has', 'been') : 18
('he', 'said') : 16

In [ ]:
print("TOP 10 TRIGRAMS")
print("=" * 40)

for gram, frequency in trigram_freq.most_common(10):

    print(gram, ":", frequency)

TOP 10 TRIGRAMS
========================================
('the', 'united', 'states') : 12
('the', 'jury', 'said') : 7
('of', 'the', 'ward') : 6
('one', 'of', 'the') : 5
('medical', 'and', 'dental') : 5
('the', 'president', 'said') : 5
('that', 'the', 'united') : 5
('the', 'secretary', 'of') : 5
('the', 'grand', 'jury') : 4
('to', 'make', 'the') : 4

In [ ]:
# Top 10 Unigrams
top_unigrams = pd.DataFrame(
    unigram_freq.most_common(10),
    columns=["Unigram", "Frequency"]
)

# Top 10 Bigrams
top_bigrams = pd.DataFrame(
    [
        (" ".join(gram), frequency)
        for gram, frequency in bigram_freq.most_common(10)
    ],
    columns=["Bigram", "Frequency"]
)

# Top 10 Trigrams
top_trigrams = pd.DataFrame(
    [
        (" ".join(gram), frequency)
        for gram, frequency in trigram_freq.most_common(10)
    ],
    columns=["Trigram", "Frequency"]
)

print("TOP 10 UNIGRAMS")
display(top_unigrams)

print("TOP 10 BIGRAMS")
display(top_bigrams)

print("TOP 10 TRIGRAMS")
display(top_trigrams)

TOP 10 UNIGRAMS

    Unigram  Frequency
0    (the,)        675
1     (of,)        315
2     (to,)        265
3      (a,)        207
4     (in,)        195
5    (and,)        174
6    (for,)        110
7   (that,)         99
8  (would,)         80
9   (said,)         76

TOP 10 BIGRAMS

      Bigram  Frequency
0     of the         95
1     in the         66
2     to the         34
3   that the         23
4     on the         23
5    for the         22
6   would be         22
7  the state         18
8   has been         18
9    he said         16

TOP 10 TRIGRAMS

              Trigram  Frequency
0   the united states         12
1       the jury said          7
2         of the ward          6
3          one of the          5
4  medical and dental          5
5  the president said          5
6     that the united          5
7    the secretary of          5
8      the grand jury          4
9         to make the          4

# Conclusion

In this lab, we performed various Natural Language Processing tasks using Python and NLTK.

1. Sentence and word tokenization were performed using the Brown Corpus.
2. Lowercase conversion, punctuation removal and stop-word removal were performed.
3. Porter stemming and WordNet lemmatization were compared.
4. Basic spelling correction was implemented using approximate string matching and the NLTK Words Corpus.
5. Unigrams, bigrams and trigrams were generated from the Brown Corpus.
6. N-gram frequencies were calculated and the top 10 N-grams were displayed.

**Name:** Satyam Kumar  
**Enrollment No.:** S24CSEU0480